name: Pull Request

on: pull_request

jobs:
  tests-lint:
    name: Run tests and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Unit Tests
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: "on"
        with:
          args: make mod_download && make test_unit_codecov
      - name: Push CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: true
      - name: Lint
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: "on"
        with:
          args: make install && make lint
      - name: Bench tests
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: "on"
        with:
          args: make install && make test_benchmark
